### ISSUE TITLE
Sitecore logging an error related to the SSL/TLS secure channel

### ISSUE THREAD

**Issue by michaellwest** [michaellwest/docker-https#3]
![image](https://user-images.githubusercontent.com/933163/76457955-b3799780-63a7-11ea-88f3-1dc8c6d9839b.png)

```text
ManagedPoolThread #0 19:04:13 INFO  Job started: Sitecore.Tasks.UrlAgent
ManagedPoolThread #0 19:04:13 INFO  Scheduling.UrlAgent started. Url: https://docker-https.dev.local/sitecore/service/keepalive.aspx
ManagedPoolThread #6 19:04:13 INFO  Job ended: Sitecore.ContentSearch.SolrProvider.Agents.IndexingStateSwitcher (units processed: )
ManagedPoolThread #0 19:04:13 ERROR Exception in UrlAgent (url: /sitecore/service/keepalive.aspx)
Exception: System.Net.WebException
Message: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Source: System
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at Sitecore.Web.WebUtil.ExecuteWebPage(String url, NameValueCollection headers)
   at Sitecore.Tasks.UrlAgent.Run()

Nested Exception

Exception: System.Security.Authentication.AuthenticationException
Message: The remote certificate is invalid according to the validation procedure.
```

**Comment by michaellwest** [comment]
Fixed.
